### ISSUE TITLE
Release needed to be compatible with Foreman again

### ISSUE THREAD

**Issue by dgoetz** [theforeman/foreman_host_extra_validator#13]
As you did the last releases, ping @evgeni and @ares. Can you do a release here as it breaks Foreman at the moment? Thanks in Advance!

See discussion and verification of it being fixed in master at https://community.theforeman.org/t/foreman3-9-unable-to-install-the-plugin-of-foreman-host-extra-validator/36521

**Comment by ares** [comment]
Here you are https://rubygems.org/gems/foreman_host_extra_validator/versions/0.2.2, AFAIK the packaging PR should pop up eventually automatically. Closing, let me know if anything else is needed.
