### ISSUE TITLE
Push git tags to github

### ISSUE THREAD

**Issue by ekohl** [theforeman/foreman_host_extra_validator#6]
Currently you can't see the releases in Github because there are no tags. It'd helpful when tags were pushed.

**Comment by traylenator** [comment]
Just looking at this - would be good to just make this an official plugin?

**Comment by ekohl** [comment]
What do you mean by official plugin? Supported in the installer etc?

**Comment by traylenator** [comment]
Our previous plugins we wrote are now maintained inside the `theforeman` name space.

**Comment by ekohl** [comment]
This plugin is already in our namespace so are you talking about other plugins? In general we're happy to accept plugins in our namespace. A post to https://community.theforeman.org/ is probably the easiest way.

**Comment by ekohl** [comment]
I at least see some tags in https://github.com/theforeman/foreman_host_extra_validator/tags so I think this can be considered done.
